config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/index'
  get 'static_pages/secret'
  devise_for :users

  root to: 'event#index'

  get 'event/index'

  

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	after_create :attendance_send

	belongs_to :user
	belongs_to :event

	def attendance_send
		AttendanceMailer.participation_email(self.user, self.event).deliver_now
		
	end
end

app/models/event.rb
class Event < ApplicationRecord
	has_many :attendances
	has_many :users, through: :attendances
	belongs_to :organizer, class_name: "User"
	validates :start_date, presence: true
	validate :is_start_date_past?
	validates :title, length: {minimum: 5, maximum: 140}, presence: true
	validates :duration,  presence: true
	validate  :is_multiple_of_5?
	validates :description, length: {in: 20..1000}, presence: true
	validates :price, length: {in: 1..1000}, presence: true
	validates :location, presence: true

	def is_start_date_past?
		if start_date < Time.now
			errors.add(:start_date, "l'évent ne peut pas se passer dans le passé")
		end
	end

	def is_multiple_of_5?
		if (duration <= 0) || (duration % 5 != 0)
			errors.add(:duration, "faut que ce soit un multiple de 5")
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	after_create :welcome_send

	has_many :attendances
	has_many :events, through: :attendances
	has_many :attendees, foreign_key: "attendee_id", class_name: "Event"
	has_many :organizers, foreign_key: "organizer_id", class_name: "Event"

	
	def welcome_send
		UserMailer.welcome_email(self).deliver_now
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_action :authenticate_user!
	
  def index
  end

  def secret
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/event/index.html.erb
<h1>Ouais gros t'es sur Lyon Events</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LyonEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    
     <%= link_to "Home", root_path %>
     <%= link_to "Creer un event", event_index_path %>
     <% if user_signed_in? %>
     <%= link_to "Mon profil", root_path %>
     <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %>
     <% else %>
     <%= link_to "S'inscrire", new_user_registration_path %>
     <%= link_to "Se connecter", new_user_session_path %>

     <% end %>
     

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    <%= debug user_signed_in? %>
    <%= debug session.to_hash %>

 </body>
</html>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>